name: Build & Deploy Github Pages

on:
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    strategy:
      matrix:
        node-version: [21]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          submodules: true

      # - name: Setup Pages
      #   uses: actions/configure-pages@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Show Directory
        run: ls -la

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install Node Dependecies with PNPM
        run: pnpm install

      - name: 'Build www with Vite'
        run: pnpm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'www'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
